config/routes.rb
Rails.application.routes.draw do
  
  devise_for :people ,:controllers => {:registrations => "registrations", :sessions => "sessions"}

  get 'welcome/index'
  post 'welcome/index'

  root 'welcome#index'

  get 'remove_member' => "groups#remove_member"

  get 'leave_group' => 'groups#leave_group'

  post 'join_via_token' => 'invites#join_via_token'

  post 'email_invite' => 'invites#email_invite'

  resources :groups
  resources :documents
  resources :users
  resources :invites

end

app/models/group.rb
class Group < ActiveRecord::Base
	has_and_belongs_to_many :documents
	#has_many :documents
	has_many :memberships
	has_many :users, through: :memberships
	accepts_nested_attributes_for :memberships

	
	has_many :devisememberships
	has_many :people, through: :devisememberships
	accepts_nested_attributes_for :devisememberships

	has_many :invites
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	
	def index
		if params['search']
			@groups = Group.where(["name LIKE ?", "%#{params['search']}%"])
		else
			@groups = Group.all
		end
	end
	def show
		if (params.has_key?(:id))
			@id = params['id']
			@group = Group.find(@id)
			@name = @group.name
			@documents = Group.find(@id).documents

			# #devise version 
			if !Devisemembership.find_by(group_id: @id).nil? && person_signed_in?
				@owners = @group.devisememberships.where(role: "owner")
				#returns a collection of Membership objects, NOT USERS.
				@memberships = @group.devisememberships.order('role DESC')
			end
		end
	end 
	def new
		@group = Group.new
		#race condition? need to double check
		@groups = Group.order(created_at: :desc).limit(10)
		respond_to do |format|
		    format.html # new.html.erb
		    format.xml  { render :xml => @group }
    	end
	end

	def create

		@group = Group.new(group_params)
		# @creator = params['creator']
		# @group.users << User.find(@creator)
		if person_signed_in?
			@group.people << current_person
		end
		#role set to owner as default  
		#when adding using to a group, just make sure to find membership using both user and group id, 
		#then change the role using update_attribute. 
		if @group.save
			# # @document.groups << @groups
			redirect_to new_group_path
		else
			render :new
		end
	end

def update
	
	@group_id = params['id']
	@group = Group.find(@group_id)
	@checked = params['owners'] #new owner's user_id passed in. 
	@new_member_id = params['members']

	if !@group.devisememberships.nil?
		for rel in @group.devisememberships
			@pid = rel.person_id.to_s
			@current_role = rel.role
			@selected_role = params['role' + @pid]
			if @current_role != @selected_role
				rel.role = @selected_role
				rel.save
				puts "role updated"
			end

		end
	end

	respond_to do |format|
	    if @group.update_attributes(group_params)
	    	@new = false
	    	begin 
	    		@group.people.find(@new_member_id)
	    	rescue ActiveRecord::RecordNotFound
	    		@new = true
	    	end 

	    	if !@new_member_id.blank? && @new
	    		puts "new member!"
	    		# @group.users << User.find(@new_member_id)
	    		@group.people << Person.find(@new_member_id)

	    		#change role to member 
	    		@devisemembership = @group.devisememberships.find_by(person_id: @new_member_id)
	    		puts @devisemembership.role
	    		@devisemembership.role = 'member'
	    		@devisemembership.save
	    		puts 'role set to member'
	    		# @group.memberships.find_by(user_id: @new_member_id).save
	    		
	    	end


	      	if !@checked.blank?
	      		begin
	      			# @group.users << User.find(@checked)
	      			@group.people << Person.find(@checked)
	      		rescue ActiveRecord::RecordNotUnique
	      			puts 'no change'
	      		end 
			    
			end
	    
		format.html { redirect_to(@group, :notice => 'Group was successfully updated.') }
		format.xml  { head :ok }
	else
	    render :edit
	end
	end
end

	def edit
		#db calls
		@id = params['id']
	    @group = Group.find(@id)
		# @users = User.all #for display in drop down menu..not ideal for now. 
		@users = Person.all #changed from User.all
		@documents = @group.documents
		@invite = Invite.new
	    if !Devisemembership.find_by(group_id: @id).nil?
	    	puts "here"
			@owners = @group.devisememberships.where(role: "owner")

			@memberships = @group.devisememberships

		else
			puts "group not found in membership"
		end

 	end

 	#remove someone from the group 
 	def remove_member
		@m_id = params[:m_id] #id of the membership in the membership join table 
		@membership = Devisemembership.find(@m_id)

		#also remove the invite entry in invites table
		@removedPerson = @membership.person_id
		@invite = Invite.find_by(recipient_id: @removedPerson)
		if @invite
			@invite.destroy
		end

		@membership.destroy

		respond_to do |format|
			format.html {redirect_to request.referrer}
			format.xml  { head :no_content }
		end
	end

	#leave group 
	def leave_group
		@gid = params[:id]
		@pid = current_person.id
		@membership = Devisemembership.find_by(person_id: @pid, group_id: @gid)

		#also remove the invite entry in invites table
		@invite = Invite.find_by(recipient_id: @pid)
		if @invite
			@invite.destroy
		end

		@membership.destroy
		flash[:success] = 'Left ' + Group.find(@gid).name.to_s 

		respond_to do |format|
			format.html {redirect_to welcome_index_path}
			format.xml  { head :no_content }
		end

	end


	private 

	def group_params
    	params.require(:group).permit(:name)
	end
end

	

app/helpers/group_helper.rb
module GroupHelper
end

app/views/groups/_home.html.erb
<div class="navigation"><%= link_to 'Home', :controller => 'welcome', :action => 'index' %> </div>
<div class="navigation"><%= link_to 'Groups', :controller => 'groups', :action => 'index' %> </div>
<div class="navigation"><%= link_to 'Documents', :controller => 'documents', :action => 'index' %> </div>

<br/>
<p></p>

app/views/groups/edit.html.erb
<%= render 'home' %>

<% if is_owner() %>


<h1>Editing Group: <%= @group.name %> </h1>

<% if !@owners.nil? %>
	Owner(s): 
	<% @owners.each do |o| %> 
		<%= Person.find(o.person_id).name %>  | 
	<% end %>
<% end %>

<%= form_for @group do |f| %>
	<p> 
		<%= f.label :name %>
		<%= f.text_field :name %> <br />
	</p>

	<p> 
	Add New Owner: <%= select_tag "owners", options_from_collection_for_select(@users, "id", "name"), :include_blank => 'User...' %>
	</p>

	<p> 
	Add New Member: <%= select_tag "members", options_from_collection_for_select(@users, "id", "name"), :include_blank => 'User...' %>
	</p>

	<h3>People </h3>
	<table>
		<tr>
			<th> Name </th>
			<th> Role </th>
			<th> Remove </th>
		</tr>
	<% if !@memberships.nil? %>
	<% @memberships.each do |m| %>
			<tr> 
				<% @person = Person.find(m.person_id) %>
				<td> <%= @person.name %></td>

				<td> <%= select_tag "role" + @person.id.to_s, options_for_select([ "owner", "member" ], m.role) %> </td> 

				<td> <%= link_to 'Remove from group', :controller => 'groups', :action => 'remove_member', :m_id => m.id %></td>
			</tr>
		<% end %>
	<% end %>
		


	</table>
	<p> <%= f.submit %> </p>
	<% end %>


<br/>

Invite by Email (existing users only)

<%= form_tag({:controller=>'invites', :action => 'email_invite'}, {:name => 'email_invite'}) do %>
	<%= hidden_field_tag :group_id, @id %>
	<%= label_tag :email %>
    <%= email_field_tag :email %>
    <%= submit_tag 'Submit' %>
<% end %>


<br/>

<% @i = Invite.find_by(group_id: @id) %>
<% if @i %>
	<%= label_tag 'Invite Link' %>
	<%= text_field_tag "Invite Link:", welcome_index_path(:invite_token => @i.token), {:size =>40, :class => 'copy-link' }%>
	<%= button_tag 'Copy', {:class =>'copy-button'}%>

<% else %>

	<%= form_for @invite , :url => invites_path do |f| %>
	    <%= f.hidden_field :group_id, :value => @id %>
	<%= f.label 'Invite Link' %>    
	<%= f.submit 'Generate'%>
	<% end %>
<% end %>

<br/>
<p></p>

<h3> Current Documents: <br/> </h3>
 
<% if !@documents.blank? %>
	<% for item in @documents %>
		<%= link_to item.title, :controller=> 'documents', :action => 'show', :id=> item.id %> <br/>
<% end %>

<% else %>
	<p> no documents found </p>

<% end %>


<% else %>

<p class = "permissionError"> You do not have permission to view this page </p>

<% end %>

<p></p>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', group_path %>

<script>
	//for invite link copy to clipboard
	//source: https://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript

	var copyButton = document.querySelector('.copy-button');

	copyButton.addEventListener('click', function(event){

		var copyLink = document.querySelector('.copy-link');
		copyLink.focus();
		copyLink.select();

		try{
			var successful = document.execCommand('copy');
			var msg = successful ? 'successful' : 'unsuccessful';
			console.log(msg);
		} catch (err){
			console.log('unable to copy')
		}

	});

</script>

app/views/groups/index.html.erb
<%= render 'home' %>
<h1> Groups </h1> 
<p class= 'warning'> SEARCHING IS CASE SENSITIVE! </p>

Search for a Group: 
<%= form_tag groups_path, :method => 'get' do %>
	<%= text_field_tag :search, params['search'] %>
	<%= submit_tag "Search" %>
<% end %>
<br/>

<%= link_to "See all groups", :controller => 'groups', :action => 'index'%> 

<h3> Listing Groups: <br/> </h3>
 
<% if !@groups.blank? %>
	<% for item in @groups %>
		<%= link_to item.name, :controller => 'groups', :action => 'show', :id => item.id %> <br/>
	<% end %>

<% else %>
	<p> no groups found </p>

<% end %>

app/views/groups/new.html.erb
Enter new group info

<%= form_for @group do |f| %>
	<p> 
		<%= f.label :group %>
		<%= f.text_field :name %> <br />
	</p>

	<p>
		<%= f.submit %>

	</p>
<% end %>

<h3> Recently created groups: <br/> </h3>
 
<% if !@groups.blank? %>
	<% for item in @groups %>
		<%= link_to item.name, :controller => 'groups', :action => 'show', :id => item.id %> <br/>
	<% end %>

<% else %>
	<p> no groups found </p>

<% end %>

app/views/groups/show.html.erb
<%= render 'home' %>

<% if(params.has_key?(:id)) %>
	<%= "Group ID: #{params[:id]}" %> <br/>
<!-- 	<% if(!@owner.nil?) %>
		Owner: <%= link_to @owner, :controller => 'users', :action => 'show', :id => @owner_id %>
	<% end %> -->

	<% if !@owners.nil? %>
		Owner(s): 
		<% @owners.each do |o| %> 
			<%= Person.find(o.person_id).name%> | 
			
		<% end %>
	<% end %>

	<h1> <%= @name %> </h1>

<% if in_group() %>

	<h2>Documents: </h2>
	<% if !@documents.nil? %>
		<% @documents.each do |doc| %>
			<% if !doc.title.nil? %>
				<%= link_to doc.title, :controller => 'documents', :action => 'show', :id => doc.id %> <br/>
			<% end %>
		<% end %>
	<% else %>
		<p> No documents to show </p>
	<% end %>

<% end %>

<h3>People </h3>
	<table>
		<tr>
			<th> Name </th>
			<th> Role </th>
		</tr>
		<% if !@memberships.nil? %>
		<% @memberships.each do |m| %>
			<tr> 
				<% @person = Person.find(m.person_id) %>
				<td> <%= @person.name %> </td>
				<td> <%= m.role %> </td> 
			</tr>
		<% end %>
	<% end %>
		


	</table>
<% end %>


<br>

<% if person_signed_in? %>
<%= link_to 'Create new Group', :controller => 'groups', :action => 'new' %>
<% end %>

<% if is_owner() %>

	<%= link_to 'Edit Current Group', :controller => 'groups', :action => 'edit' %>
<% end %>  

<p>
<% if in_group() %>
	<%= link_to 'Leave Group', :controller => 'groups', :action => 'leave_group', :id => params[:id] %>
<% end %>
</p>