config/routes.rb
Rails.application.routes.draw do
  
  devise_for :people ,:controllers => {:registrations => "registrations", :sessions => "sessions"}

  get 'welcome/index'
  post 'welcome/index'

  root 'welcome#index'

  get 'remove_member' => "groups#remove_member"

  get 'leave_group' => 'groups#leave_group'

  post 'join_via_token' => 'invites#join_via_token'

  post 'email_invite' => 'invites#email_invite'

  resources :groups
  resources :documents
  resources :users
  resources :invites

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController


  def index
  	if person_signed_in?
  		@mygroups = Person.find(current_person.id).groups.order('role DESC')
      @token = params[:invite_token]
      puts @token

  		#note: this implementation is temporary but if we want to allow auto join, group name has to be unique
      begin
    		@groupName = params[:groupName]
    		if @groupName && Group.find_by(name: @groupName)
    			@group = Group.find_by(name: @groupName)
    			current_person.groups << @group

    			#set role to member
    			@devisemembership = @group.devisememberships.find_by(person_id: @current_person.id)
      		puts @devisemembership.role
      		@devisemembership.role = 'member'
      		@devisemembership.save
      		puts 'role set to member'
      		flash[:success] = 'Successfully Joined Group!'

      	elsif @groupName && Group.find_by(name: @groupName).nil?
          flash[:error] = 'Group not found!'
      	end
      rescue ActiveRecord::RecordNotUnique
        flash[:error] = 'Already in Group!'
      end



  	end
  end


end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
	<% if person_signed_in? %>
	<h1>Welcome <%= current_person.name %></h1>
	<ul>
		<li> 
			<%= link_to 'Sign Out', destroy_person_session_path, method: :delete %>
		</li>
		<li> <%= current_person.email %></li>
		<li> <%= link_to 'Edit Account', edit_person_registration_path %></li>
	</ul>

	<p>
		Enter token to join group. PLEASE BE CAREFUL OF EXTRA SPACES
		<%= form_tag({:controller=>'invites', :action => 'join_via_token'}, {:name => 'join-via-token'}) do %>
			<%= label_tag 'Token:' %>
			<% if params[:invite_token] %>
				<%= text_field_tag 'token', params[:invite_token] %>
					<script>
						window.onload = function(){
							document.forms['join-via-token'].submit();
						}
					</script>
			<% else %>
		    <%= text_field_tag 'token' %>
		    <% end %>
		    <%= submit_tag 'Submit' %>
		<% end %>

	</p>

<p>
<% # original group joining method: auto join by entering group name %>

	<%= form_tag do %>
	Join group by entering name (case sensitive)
		<% label_tag 'groupName' %>
		<%= text_field_tag 'groupName'%>
		<%= submit_tag 'Join'%>
	<% end %>

</p>


<div class= "group">

	<h2> Groups </h2>
	<ul>
		<% @mygroups.each do |g| %>

			<li><%= link_to g.name, :controller => 'groups', :action => 'show', :id => g.id%> (<%= Devisemembership.find_by(group_id: g.id, person_id: current_person.id).role %>) </li>
		<% end %>

		</ul>
	<br>
</div>

<div class="document"> 
	<h2> Documents </h2>
	<p>
		<% @mygroups.each do |g| %>
			<% g.documents.each do |d| %>
				<%= link_to d.title, :controller => 'documents', :action => 'show', :id => d.id %> <br/>
			<% end %>
		<% end %>


	</p>
</div>

<div class="create">
	<%= link_to'Create Documents', :controller => 'documents', :action =>'new' %>

	<br/>
	<%= link_to'Create Groups', :controller => 'groups', :action =>'new' %>
</div>

	<% else %>


		<%= link_to 'Sign in', new_person_session_path(invite_token: params[:invite_token]) %> <br/>

		 <%= link_to 'Sign up', new_person_registration_path(invite_token: params[:invite_token]) %> <br/>

	<% end %>