config/routes.rb
Rails.application.routes.draw do
  
  devise_for :people ,:controllers => {:registrations => "registrations", :sessions => "sessions"}

  get 'welcome/index'
  post 'welcome/index'

  root 'welcome#index'

  get 'remove_member' => "groups#remove_member"

  get 'leave_group' => 'groups#leave_group'

  post 'join_via_token' => 'invites#join_via_token'

  post 'email_invite' => 'invites#email_invite'

  resources :groups
  resources :documents
  resources :users
  resources :invites

end

app/models/document.rb
class Document < ActiveRecord::Base
	has_and_belongs_to_many :groups
	#belongs_to :groups
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
	def index
		if params['search']
			@documents = Document.where(["title LIKE ?", "%#{params['search']}%"])
		else
			@documents = Document.all
		end
	end

	def show
		if (params.has_key?(:id))
			@id = params['id']
			@title = Document.find(@id).title
			@body = Document.find(@id).body
			@groups = Document.find(@id).groups
			

			respond_to do |format|
		      format.html # show.html.erb
		      format.xml  { render :xml => @document }
    		end
		end
  	end
	
	def new
		@document = Document.new
		@documents = Document.all
		if person_signed_in?
			@groups = Person.find(current_person.id).groups
		# puts @groups
		end

		respond_to do |format|
     		format.html # new.html.erb
     		format.xml  { render :xml => @document }
   		end

	end

	def create 
		@document = Document.new(document_params)
		# params['groups'].each do |k|
		# 	@document.groups << Group.find_by_name(k)
		# end
		@checked = params['groups']
		@document.groups << Group.find(@checked)

		if @document.save
			# # @document.groups << @groups
			redirect_to new_document_path
		else
			render :new
		end
	end

	def update
	    # params[:document][:group_id] ||= []
	    @document = Document.find(params['id'])
	 #    params['groups'].each do |k|
		# 	@document.groups << Group.find_by_name(k)
		# end
		#params = what's being passed from the form 
		@checked = params['groups']
		# @alreadyInGroup = false
		
		#ensures document is only added to the group once. 
		#alternate solution: specify custom primary key on join table
		begin
			@document.groups.find(@checked)
			
		rescue ActiveRecord::RecordNotFound
			@document.groups << Group.find(@checked)
			
		else
		puts "ERROR"
		end
		# else
		# 	@document.groups << Group.find(@checked)
		# end

	    respond_to do |format|
	      if @document.update_attributes(document_params)
	        format.html { redirect_to(@document, :notice => 'Document was successfully updated.') }
	        format.xml  { head :ok }
	      else
	        render :edit
	    
	      end
	    end
	end

	def edit
		#db calls
	    # @groups = Group.all
	    @groups = Person.find(current_person.id).groups
	    @document = Document.find(params['id'])
	    @current_groups = @document.groups
	    # puts @current_group.nil?

	    #usually works with just first clause but needed 2nd part for document id = 9?
	    if !@current_groups.nil? && @current_groups.length > 0 
	    	puts "has current groups"
		    @first = @current_groups.first.id
		else
			@first = @groups.first.id
			puts "no groups"
		end
 	end

	private 

	def document_params
		#changing stuff in db needs to permit 
	    params.require(:document).permit(:title, :body, groups: :group_id)
	end


end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/edit.html.erb
<%= render 'home' %>

<h1>Editing Document</h1>

Current Groups: 
<% @current_groups.each do |g| %>
	<%= g.name %> <br/>
<% end %>

<%= form_for @document do |f| %>
	<p> 
		<%= f.label :title %>
		<%= f.text_field :title %> <br />
	</p>

	<p> 
		<%= f.label :body %>
		<%= f.text_area :body %> <br />
	</p>
	<p> 
	

	<%= select_tag "groups", options_from_collection_for_select(@groups, "id", "name", @first) %>
	
	</p>

	<p>
		<%= f.submit %>

	</p>
<% end %>



<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<%= render 'home' %>

<h1> Documents </h1> 

Search for a Document: 
<%= form_tag documents_path, :method => 'get' do %>
	<%= text_field_tag :search, params['search'] %>
	<%= submit_tag "Search" %>
<% end %>
<br/>

<%= link_to "See all documents", :controller => 'documents', :action => 'index'%> 

<h3> Listing Documents: <br/> </h3>
 
<% if !@documents.blank? %>
	<% for item in @documents %>
		<%= link_to item.title, :controller => 'documents', :action => 'show', :id => item.id %> <br/>
	<% end %>

<% else %>
	<p> no documents found </p>

<% end %>

app/views/documents/new.html.erb
<%= render 'home' %>
<% if person_signed_in? %>

Enter new document info

<%= form_for @document do |f| %>
	<p> 
		<%= f.label :title %>
		<%= f.text_field :title %> <br />
	</p>

	<p> 
		<%= f.label :body %>
		<%= f.text_area :body %> <br />
	</p>
	<!-- <p> 


	<% @groups.each do |g| %>
		<%= f.label g.name %> 
		<%= check_box_tag "groups[#{g.name}]", g.name %>
		<br/>
	<% end %>
	</p> -->
	<p> 
	

	<%= select_tag "groups", options_from_collection_for_select(@groups, "id", "name"), include_blank: true %>
	
	</p>
	

	<p>
		<%= f.submit %>

	</p>
<% end %>



Current Documents: <br/>
 
<% if !@documents.blank? %>
	<% for item in @documents %>
		<%= link_to item.title, :controller=> 'documents', :action => 'show', :id=> item.id %> <br/>
<% end %>

<% else %>
	<p> no documents found </p>

<% end %>
<% else %>
<p class = "permissionError"> Please sign in to see this page </p>
<% end %>

app/views/documents/show.html.erb
<%= render 'home' %>

<% if(params.has_key?(:id)) %>
	<%= "document ID: #{params[:id]}" %> <br/>
	<h1> <%= @title %> </h1>
	<p> <%= @body %> </p>

	<h2>Groups: </h2>
	<% @groups.each do |g| %>
		<% if !g.name.nil? %>
			<%= link_to g.name, :controller => 'groups', :action => 'show', :id => g.id %> <br/>
		<% end %>
	<% end %>

<% end %>


<br>
<%= link_to 'Create new Doc', :controller => 'documents', :action => 'new' %>
<%= link_to 'Edit Current Doc', :controller => 'documents', :action => 'edit' %>